services:
  ## shared services

  mysql:
    image: mysql:9.4.0
    # ports:
    #   - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./migrations/base.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - .db-data:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:8.2.2
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    user: root
    volumes:
      - .redis-data:/data
    command:
      - sh
      - -c
      - |
        if [ -n "$${REDIS_PASS}" ]; then
          redis-server --requirepass "$${REDIS_PASS}"
        else
          redis-server
        fi

  # Cloudflare tunneling via Zero-Trust
  # cloudflared:
  #   container_name: cloudflared
  #   image: cloudflare/cloudflared:2025.9.1
  #   restart: unless-stopped
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  ## application services

  bancho:
    # we also have a public image: osuakatsuki/bancho.py:latest
    image: bancho:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true
    init: true
    volumes:
      - .:/srv/root
      - .data:/srv/root/.data
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - OSU_API_KEY=${OSU_API_KEY}
      - MIRROR_SEARCH_ENDPOINT=${MIRROR_SEARCH_ENDPOINT}
      - MIRROR_DOWNLOAD_ENDPOINT=${MIRROR_DOWNLOAD_ENDPOINT}
      - DOMAIN=${DOMAIN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - SEASONAL_BGS=${SEASONAL_BGS}
      - MENU_ICON_URL=${MENU_ICON_URL}
      - MENU_ONCLICK_URL=${MENU_ONCLICK_URL}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_APP_KEY=${DATADOG_APP_KEY}
      - DEBUG=${DEBUG}
      - REDIRECT_OSU_URLS=${REDIRECT_OSU_URLS}
      - PP_CACHED_ACCS=${PP_CACHED_ACCS}
      - DISALLOWED_NAMES=${DISALLOWED_NAMES}
      - DISALLOWED_PASSWORDS=${DISALLOWED_PASSWORDS}
      - DISALLOW_OLD_CLIENTS=${DISALLOW_OLD_CLIENTS}
      - DISALLOW_INGAME_REGISTRATION=${DISALLOW_INGAME_REGISTRATION}
      - DISCORD_AUDIT_LOG_WEBHOOK=${DISCORD_AUDIT_LOG_WEBHOOK}
      - AUTOMATICALLY_REPORT_PROBLEMS=${AUTOMATICALLY_REPORT_PROBLEMS}
      - LOG_WITH_COLORS=${LOG_WITH_COLORS}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - DEVELOPER_MODE=${DEVELOPER_MODE}
      # - DB_USE_SSL=${DB_USE_SSL}

  guweb:
    build:
      context: ./guweb
      dockerfile: Dockerfile
    image: guweb:latest
    ports:
      - "${GUWEB_PORT:-8000}:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true
    init: true
    volumes:
      - ./guweb:/srv/root
      - ./guweb/.data:/srv/root/.data
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASS=${REDIS_PASS}
      - GUWEB_APP_NAME=${GUWEB_APP_NAME:-bancho.py}
      - GUWEB_SECRET_KEY=${GUWEB_SECRET_KEY:-changeme}
      - GUWEB_HCAPTCHA_SITEKEY=${GUWEB_HCAPTCHA_SITEKEY:-changeme}
      - GUWEB_HCAPTCHA_SECRET=${GUWEB_HCAPTCHA_SECRET:-changeme}
      - DOMAIN=${DOMAIN}
      - GUWEB_DEBUG=${GUWEB_DEBUG:-false}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_EMAIL_PASSWORD=${SENDER_EMAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - IMAP_HOST=${IMAP_HOST:-imap.gmail.com}
      - IMAP_PORT=${IMAP_PORT:-993}
      - EMAIL_VERIFY_KEY_LENGTH=${EMAIL_VERIFY_KEY_LENGTH:-32}
      - SENT_EMAIL_TIMEOUT=${SENT_EMAIL_TIMEOUT:-300}
      - DISCORD_EMAIL_LOG_WEBHOOK=${DISCORD_EMAIL_LOG_WEBHOOK}
      - GUWEB_GITHUB=${GUWEB_GITHUB}
      - GUWEB_DISCORD=${GUWEB_DISCORD}
      - GUWEB_YOUTUBE=${GUWEB_YOUTUBE}
      - GUWEB_TWITTER=${GUWEB_TWITTER}
      - GUWEB_INSTAGRAM=${GUWEB_INSTAGRAM}
      - GUWEB_TWITCH=${GUWEB_TWITCH}
      - GUWEB_OSUSERVER=${GUWEB_OSUSERVER}
      - GUWEB_DONATE=${GUWEB_DONATE}

volumes:
  data:
  db-data:
  redis-data:
